### ISSUE TITLE
Softlock in MAP03: Tesla

### ISSUE THREAD

**Issue by atalarikt99** [chutzcraft/3DGE64#1] opened 2022-11-28 05:52 UTC
It is possible to get softlocked in the platform with two elevators by pushing a switch on an elevator below and dropping down as the elevator is ascending. Since you cannot drop down from the platform, this effectively softlocks you.

Perhaps the elevator speed could be increased or another switch(es) could be added to anticipate this.

**Comment by chutzcraft** [comment] 2023-10-12 06:44
Thank you for finding this bug! I wouldnt have ever caught it trying to play things as intended. The more playtesting, the better.

-Increasing the speed of the elevator breaks the elevator entirely, trapping the player inside.

 To rectify this issue:

I've added a new line set of linedefs and restructured the elevator entirely. It now has a sliding gate in front of it that must be closed before the elevator moves.

You can find this area fixed in the next beta coming out very soon. Thank you!

**Closed as completed** 2023-10-12 06:45 UTC
